# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "tavern-minimal"
  config.vm.box_url = "https://www.dropbox.com/s/xnayxfshxobvrsu/tavern-minimal.box"
  config.vm.hostname = "Tavern.local"
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.network :forwarded_port, host: 8080, guest: 80
end
