#! /bin/sh

### BEGIN INIT INFO
# Provides:          nginx
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the nginx web server
# Description:       starts nginx using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/nginx/sbin/nginx
NAME=nginx
DESC=nginx

mkdir -p /var/run/nginx
test -x $DAEMON || exit 0

case "$1" in
  start)
    echo -n "Starting $DESC: "
        /opt/nginx/sbin/nginx -c /opt/nginx/conf/nginx.conf &
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
        killall nginx
    echo "$NAME."
    ;;
  restart|force-reload)
    echo -n "Restarting $DESC: "
        killall nginx
    sleep 1
        /opt/nginx/sbin/nginx -c /opt/nginx/conf/nginx.conf
    echo "$NAME."
    ;;
  reload)
      echo -n "Reloading $DESC configuration: "
        killall -HUP nginx
      echo "$NAME."
      ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload|force-reload|status}" >&2
    exit 1
    ;;
esac

exit 0

